// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"
#include "ui_ScreenButtons.h"
#include "ui_ScreenPlayer.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_icon_noptepad_png);    // assets/icon_noptepad.png
LV_IMG_DECLARE(ui_img_icon_cacl_png);    // assets/icon_cacl.png
LV_IMG_DECLARE(ui_img_icon_player_png);    // assets/icon_player.png
LV_IMG_DECLARE(ui_img_icon_back_png);    // assets/icon_back.png
LV_IMG_DECLARE(ui_img_1156012293);    // assets/media_thumb~1.png
LV_IMG_DECLARE(ui_img_827955121);    // assets/上一首 (1).png
LV_IMG_DECLARE(ui_img_1676589243);    // assets/暂停 (1).png
LV_IMG_DECLARE(ui_img_853450402);    // assets/下一首.png

// FONTS
LV_FONT_DECLARE(ui_font_Font15);
LV_FONT_DECLARE(ui_font_FontNotepad);
LV_FONT_DECLARE(ui_font_FontNotepad20);
LV_FONT_DECLARE(ui_font_FontTime36);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
