// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREENPLAYER_H
#define UI_SCREENPLAYER_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenPlayer
extern void ui_ScreenPlayer_screen_init(void);
extern void ui_ScreenPlayer_screen_destroy(void);
extern lv_obj_t * ui_ScreenPlayer;
extern lv_obj_t * ui_Image5;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Image10;
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Image6;
extern lv_obj_t * ui_Button9;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Container3;
extern lv_obj_t * ui_Label6;
extern lv_obj_t * ui_Label9;
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui_Label8;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ScreenMusic;
extern lv_obj_t * uic_Slider2;
extern lv_obj_t * uic_Label8;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

