// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_ButtonBack;
lv_obj_t * uic_ButtonPlayer;
lv_obj_t * uic_ButtonCacl;
lv_obj_t * uic_ButtonNotepad;
lv_obj_t * uic_ScreenButtons;
lv_obj_t * ui_ScreenButtons = NULL;
lv_obj_t * ui_Container9 = NULL;
lv_obj_t * ui_ContainerMain2 = NULL;
lv_obj_t * ui_Button4 = NULL;
lv_obj_t * ui_Image7 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Button5 = NULL;
lv_obj_t * ui_Image3 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Button6 = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_ContainerMain3 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Image2 = NULL;
lv_obj_t * ui_Label2 = NULL;
// event funtions

// build funtions

void ui_ScreenButtons_screen_init(void)
{
    ui_ScreenButtons = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenButtons, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container9 = lv_obj_create(ui_ScreenButtons);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, 454);
    lv_obj_set_height(ui_Container9, 299);
    lv_obj_set_x(ui_Container9, -2);
    lv_obj_set_y(ui_Container9, -2);
    lv_obj_set_align(ui_Container9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container9, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_Container9, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_clear_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerMain2 = lv_obj_create(ui_Container9);
    lv_obj_remove_style_all(ui_ContainerMain2);
    lv_obj_set_width(ui_ContainerMain2, 447);
    lv_obj_set_height(ui_ContainerMain2, 130);
    lv_obj_set_x(ui_ContainerMain2, 1);
    lv_obj_set_y(ui_ContainerMain2, -107);
    lv_obj_set_align(ui_ContainerMain2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerMain2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ContainerMain2, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerMain2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button4 = lv_btn_create(ui_ContainerMain2);
    lv_obj_set_width(ui_Button4, 124);
    lv_obj_set_height(ui_Button4, 141);
    lv_obj_set_x(ui_Button4, -160);
    lv_obj_set_y(ui_Button4, -27);
    lv_obj_set_align(ui_Button4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Button4, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Button4, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image7 = lv_img_create(ui_Button4);
    lv_img_set_src(ui_Image7, &ui_img_icon_noptepad_png);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image7, -7);
    lv_obj_set_y(ui_Image7, -29);
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Image7, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_Image7, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label7 = lv_label_create(ui_Button4);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, -1);
    lv_obj_set_y(ui_Label7, 57);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "记事本");
    lv_obj_set_style_text_font(ui_Label7, &ui_font_FontNotepad20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button5 = lv_btn_create(ui_ContainerMain2);
    lv_obj_set_width(ui_Button5, 124);
    lv_obj_set_height(ui_Button5, 141);
    lv_obj_set_x(ui_Button5, -55);
    lv_obj_set_y(ui_Button5, -27);
    lv_obj_set_align(ui_Button5, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Button5, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Button5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button5, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image3 = lv_img_create(ui_Button5);
    lv_img_set_src(ui_Image3, &ui_img_icon_cacl_png);
    lv_obj_set_width(ui_Image3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image3, -7);
    lv_obj_set_y(ui_Image3, -29);
    lv_obj_set_align(ui_Image3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Image3, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_Image3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_Image3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_Button5);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -1);
    lv_obj_set_y(ui_Label3, 57);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "计算器");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_FontNotepad20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button6 = lv_btn_create(ui_ContainerMain2);
    lv_obj_set_width(ui_Button6, 124);
    lv_obj_set_height(ui_Button6, 141);
    lv_obj_set_x(ui_Button6, -55);
    lv_obj_set_y(ui_Button6, -27);
    lv_obj_set_align(ui_Button6, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Button6, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Button6, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_Button6);
    lv_img_set_src(ui_Image4, &ui_img_icon_player_png);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image4, -7);
    lv_obj_set_y(ui_Image4, -29);
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Image4, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_Image4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -1);
    lv_obj_set_y(ui_Label4, 57);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "播放器");
    lv_obj_set_style_text_font(ui_Label4, &ui_font_FontNotepad20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerMain3 = lv_obj_create(ui_ScreenButtons);
    lv_obj_remove_style_all(ui_ContainerMain3);
    lv_obj_set_width(ui_ContainerMain3, 447);
    lv_obj_set_height(ui_ContainerMain3, 130);
    lv_obj_set_x(ui_ContainerMain3, -3);
    lv_obj_set_y(ui_ContainerMain3, 77);
    lv_obj_set_align(ui_ContainerMain3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ContainerMain3, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_ContainerMain3, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerMain3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button2 = lv_btn_create(ui_ContainerMain3);
    lv_obj_set_width(ui_Button2, 124);
    lv_obj_set_height(ui_Button2, 141);
    lv_obj_set_x(ui_Button2, -160);
    lv_obj_set_y(ui_Button2, -27);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Button2, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Button2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image2 = lv_img_create(ui_Button2);
    lv_img_set_src(ui_Image2, &ui_img_icon_back_png);
    lv_obj_set_width(ui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image2, -7);
    lv_obj_set_y(ui_Image2, -29);
    lv_obj_set_align(ui_Image2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Image2, LV_FLEX_FLOW_COLUMN_WRAP);
    lv_obj_set_flex_align(ui_Image2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_add_flag(ui_Image2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -1);
    lv_obj_set_y(ui_Label2, 57);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "返回");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_FontNotepad20, LV_PART_MAIN | LV_STATE_DEFAULT);

    uic_ScreenButtons = ui_ScreenButtons;
    uic_ButtonNotepad = ui_Button4;
    uic_ButtonCacl = ui_Button5;
    uic_ButtonPlayer = ui_Button6;
    uic_ButtonBack = ui_Button2;

}

void ui_ScreenButtons_screen_destroy(void)
{
    if(ui_ScreenButtons) lv_obj_del(ui_ScreenButtons);

    // NULL screen variables
    uic_ScreenButtons = NULL;
    ui_ScreenButtons = NULL;
    ui_Container9 = NULL;
    ui_ContainerMain2 = NULL;
    uic_ButtonNotepad = NULL;
    ui_Button4 = NULL;
    ui_Image7 = NULL;
    ui_Label7 = NULL;
    uic_ButtonCacl = NULL;
    ui_Button5 = NULL;
    ui_Image3 = NULL;
    ui_Label3 = NULL;
    uic_ButtonPlayer = NULL;
    ui_Button6 = NULL;
    ui_Image4 = NULL;
    ui_Label4 = NULL;
    ui_ContainerMain3 = NULL;
    uic_ButtonBack = NULL;
    ui_Button2 = NULL;
    ui_Image2 = NULL;
    ui_Label2 = NULL;

}
