// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREENBUTTONS_H
#define UI_SCREENBUTTONS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenButtons
extern void ui_ScreenButtons_screen_init(void);
extern void ui_ScreenButtons_screen_destroy(void);
extern lv_obj_t * ui_ScreenButtons;
extern lv_obj_t * ui_Container9;
extern lv_obj_t * ui_ContainerMain2;
extern lv_obj_t * ui_Button4;
extern lv_obj_t * ui_Image7;
extern lv_obj_t * ui_Label7;
extern lv_obj_t * ui_Button5;
extern lv_obj_t * ui_Image3;
extern lv_obj_t * ui_Label3;
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Image4;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_ContainerMain3;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Image2;
extern lv_obj_t * ui_Label2;
// CUSTOM VARIABLES
extern lv_obj_t * uic_ScreenButtons;
extern lv_obj_t * uic_ButtonNotepad;
extern lv_obj_t * uic_ButtonCacl;
extern lv_obj_t * uic_ButtonPlayer;
extern lv_obj_t * uic_ButtonBack;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

