// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_Label8;
lv_obj_t * uic_Slider2;
lv_obj_t * uic_ScreenMusic;
lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Slider1 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Image10 = NULL;
lv_obj_t * ui_Button8 = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_Button9 = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Slider2 = NULL;
lv_obj_t * ui_Label8 = NULL;
// event funtions

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image5 = lv_img_create(ui_Screen2);
    lv_img_set_src(ui_Image5, &ui_img_1156012293);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image5, -121);
    lv_obj_set_y(ui_Image5, -59);
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container1 = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 451);
    lv_obj_set_height(ui_Container1, 20);
    lv_obj_set_x(ui_Container1, 0);
    lv_obj_set_y(ui_Container1, 63);
    lv_obj_set_align(ui_Container1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -252);
    lv_obj_set_y(ui_Label1, 86);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "00:24");

    ui_Slider1 = lv_slider_create(ui_Container1);
    lv_slider_set_value(ui_Slider1, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 348);
    lv_obj_set_height(ui_Slider1, 2);
    lv_obj_set_x(ui_Slider1, 2);
    lv_obj_set_y(ui_Slider1, 9);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);

    ui_Label5 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "09:88");

    ui_Container2 = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 361);
    lv_obj_set_height(ui_Container2, 47);
    lv_obj_set_x(ui_Container2, -5);
    lv_obj_set_y(ui_Container2, 108);
    lv_obj_set_align(ui_Container2, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container2, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button1 = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_Button1, 42);
    lv_obj_set_height(ui_Button1, 42);
    lv_obj_set_x(ui_Button1, 69);
    lv_obj_set_y(ui_Button1, -36);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Button1, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Button1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image10 = lv_img_create(ui_Button1);
    lv_img_set_src(ui_Image10, &ui_img_827955121);
    lv_obj_set_width(ui_Image10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image10, -8);
    lv_obj_set_y(ui_Image10, 0);
    lv_obj_set_align(ui_Image10, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image10, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button8 = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_Button8, 42);
    lv_obj_set_height(ui_Button8, 42);
    lv_obj_set_x(ui_Button8, 69);
    lv_obj_set_y(ui_Button8, -36);
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Button8, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Button8, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_img_create(ui_Button8);
    lv_img_set_src(ui_Image6, &ui_img_1676589243);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image6, -8);
    lv_obj_set_y(ui_Image6, 0);
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button9 = lv_btn_create(ui_Container2);
    lv_obj_set_width(ui_Button9, 42);
    lv_obj_set_height(ui_Button9, 42);
    lv_obj_set_x(ui_Button9, 69);
    lv_obj_set_y(ui_Button9, -36);
    lv_obj_set_align(ui_Button9, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Button9, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Button9, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button9, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button9, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image8 = lv_img_create(ui_Button9);
    lv_img_set_src(ui_Image8, &ui_img_853450402);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image8, -8);
    lv_obj_set_y(ui_Image8, 0);
    lv_obj_set_align(ui_Image8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Container3 = lv_obj_create(ui_Screen2);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 207);
    lv_obj_set_height(ui_Container3, 55);
    lv_obj_set_x(ui_Container3, 107);
    lv_obj_set_y(ui_Container3, -120);
    lv_obj_set_align(ui_Container3, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label6 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label6, 198);
    lv_obj_set_height(ui_Label6, 26);
    lv_obj_set_x(ui_Label6, -1);
    lv_obj_set_y(ui_Label6, -4);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Label6, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Label6, "音乐播放器歌曲放器歌曲音乐播放器歌曲放器歌曲");
    lv_obj_set_scrollbar_mode(ui_Label6, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_dir(ui_Label6, LV_DIR_RIGHT);
    lv_obj_set_scroll_snap_x(ui_Label6, LV_SCROLL_SNAP_CENTER);
    lv_obj_set_style_text_font(ui_Label6, &ui_font_FontNotepad20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_Label9, 126);
    lv_obj_set_height(ui_Label9, 20);
    lv_obj_set_x(ui_Label9, -2);
    lv_obj_set_y(ui_Label9, -7);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Label9, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Label9, "艺人名称歌词");
    lv_obj_set_style_text_align(ui_Label9, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label9, &ui_font_Font15, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider2 = lv_slider_create(ui_Screen2);
    lv_slider_set_value(ui_Slider2, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2, 158);
    lv_obj_set_height(ui_Slider2, 7);
    lv_obj_set_x(ui_Slider2, 100);
    lv_obj_set_y(ui_Slider2, -35);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_CENTER);

    ui_Label8 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 205);
    lv_obj_set_y(ui_Label8, -36);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "100");

    uic_ScreenMusic = ui_Screen2;
    uic_Slider2 = ui_Slider2;
    uic_Label8 = ui_Label8;

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    uic_ScreenMusic = NULL;
    ui_Screen2 = NULL;
    ui_Image5 = NULL;
    ui_Container1 = NULL;
    ui_Label1 = NULL;
    ui_Slider1 = NULL;
    ui_Label5 = NULL;
    ui_Container2 = NULL;
    ui_Button1 = NULL;
    ui_Image10 = NULL;
    ui_Button8 = NULL;
    ui_Image6 = NULL;
    ui_Button9 = NULL;
    ui_Image8 = NULL;
    ui_Container3 = NULL;
    ui_Label6 = NULL;
    ui_Label9 = NULL;
    uic_Slider2 = NULL;
    ui_Slider2 = NULL;
    uic_Label8 = NULL;
    ui_Label8 = NULL;

}
