// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_Button3;
lv_obj_t * uic_LabelTime;
lv_obj_t * uic_Screen1;
lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_LabelTime = NULL;
lv_obj_t * ui_Button3 = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTime = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_LabelTime, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTime, -84);
    lv_obj_set_y(ui_LabelTime, -118);
    lv_obj_set_align(ui_LabelTime, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelTime, "23:58:46");
    lv_obj_set_style_text_font(ui_LabelTime, &ui_font_FontTime36, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button3 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button3, 100);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_x(ui_Button3, 181);
    lv_obj_set_y(ui_Button3, 121);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    uic_Screen1 = ui_Screen1;
    uic_LabelTime = ui_LabelTime;
    uic_Button3 = ui_Button3;

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    uic_Screen1 = NULL;
    ui_Screen1 = NULL;
    uic_LabelTime = NULL;
    ui_LabelTime = NULL;
    uic_Button3 = NULL;
    ui_Button3 = NULL;

}
